### ISSUE TITLE
PDDocument.load(file) isnt a method (PDFBox)

### ISSUE THREAD

**Issue by boholder** [awhipp/pdf-to-pptx-converter#1]
This error occurred while compiling the code with maven.

According to https://stackoverflow.com/questions/67069254/pddocument-loadfile-isnt-a-method-pdfbox
Simply replace `PDDocument.load(file)` with `Loader.loadPDF(file)` can resolve it, so it did.

Thank you for this convenient tool.

**Comment by awhipp** [comment]
Thanks. I have not been keeping up with this application as it was a one-off, but good to know.

It's an artifact of:
		<dependency>
		  <groupId>org.apache.pdfbox</groupId>
		  <artifactId>pdfbox</artifactId>
		  <version>[1.8.16,)</version>
		</dependency>

It has an unbound max version.
